version: '0.1pre.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" -DMOCKTURTLE_TEST=ON .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\test\%CONFIGURATION%\run_tests.exe'
